### ISSUE TITLE
Problème de dates

### ISSUE THREAD

**Issue by ptrouillard** [amauryleclerc/banana-front#2]
Lorsque je créé un sprint avec les dates suivantes : 08/05/2017 au 26/05/2017, en mode édition c'est OK. En revanche quand je sors du mode édition, les dates deviennent : 08/07/2017 au 26/07/2017

**Comment by amauryleclerc** [comment]
solve with 7b5b904cd0bca4e7b1c844cd1d255262dc9bb13e
